version: "3.9"

services:
  login-db-service:
    image: postgres:17
    container_name: login-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: surveys_db
      POSTGRES_USER: surveys_user
      POSTGRES_PASSWORD: surveys_password
    ports:
      - "5432:5432"
    volumes:
      - login-db-data:/var/lib/postgresql/data

volumes:
  login-db-data:
