/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateTaskDto } from '../model/models';
import { PageTaskDto } from '../model/models';
import { TaskDto } from '../model/models';
import { UpdateTaskDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TaskControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/tasks
     * @param createTaskDto 
     */
    createTask(createTaskDto: CreateTaskDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint delete /api/v1/tasks/{id}
     * @param id 
     */
    deleteTask(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/v1/tasks
     * @param page 
     * @param size 
     */
    getAllTasks(page?: number, size?: number, extraHttpRequestParams?: any): Observable<PageTaskDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/tasks/{id}
     * @param id 
     */
    getTaskById(id: number, extraHttpRequestParams?: any): Observable<TaskDto>;

    /**
     * 
     * 
     * @endpoint put /api/v1/tasks/{id}
     * @param id 
     * @param updateTaskDto 
     */
    updateTask(id: number, updateTaskDto: UpdateTaskDto, extraHttpRequestParams?: any): Observable<{}>;

}
