/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthenticationResponseDto } from '../model/models';
import { LoginDto } from '../model/models';
import { RegistrationDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/users/login
     * @param loginDto 
     */
    login(loginDto: LoginDto, extraHttpRequestParams?: any): Observable<AuthenticationResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/v1/users/registration
     * @param registrationDto 
     */
    register(registrationDto: RegistrationDto, extraHttpRequestParams?: any): Observable<{}>;

}
