spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/surveys_db
    username: surveys_user
    password: surveys_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # auto create/update schema
    show-sql: true       # show SQL in console
    properties:
      hibernate:
        format_sql: true # pretty-print SQL
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true       # disable Flyway completely

auth:
  token-expiration-hours: 1
  jwt-secret-key: gfsjhdgfhjsgfkjsagdjfgsdjfgsakjfg4234234h23j432h4j234jh23g4hjdsyusaufaugyfuds

cors:
  allowed-origins: http://localhost:4200,http://example.com
